# Generated by Django 3.2.13 on 2022-10-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
